---
- hosts: web
  become: true
  tasks:
  - name: create file
    file:
      path: "index.html"
      state: touch
  - name: copy content
    copy:
      dest: "index.html"
      content: |
        Hello World...!
  - name: Install nginx
    apt:
      name: nginx
      state: latest
    become: yes

  - name: Insert Index Page
    template:
      src: index.html
      dest: /var/www/html/index.html

  - name: Start NGiNX
    service:
      name: nginx
      state: started

